name: Setup Environment
description: Setup Rust, Solana CLI, Node.js, and Light Protocol tools for testing

inputs:
  cache-workspaces:
    description: "Rust workspaces to cache (format: 'path -> target')"
    required: false
    default: |
      . -> target
      examples/rust -> target
  rust-toolchain:
    description: "Rust toolchain version"
    required: false
    default: "1.90.0"
  solana-cli-version:
    description: "Solana CLI version"
    required: false
    default: "2.3.11"
  node-version:
    description: "Node.js version to install"
    required: false
    default: "20"
  install-light-cli:
    description: "Install Light Protocol CLI"
    required: false
    default: "true"
  install-pnpm:
    description: "Install pnpm package manager"
    required: false
    default: "false"
  pnpm-version:
    description: "pnpm version to install"
    required: false
    default: "9.10.0"
  photon-indexer:
    description: "Install Photon indexer (required for compression tests)"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        components: rustfmt, clippy
        cache-workspaces: ${{ inputs.cache-workspaces }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Solana CLI tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/solana/
          ~/.local/share/solana/
        key: solana-cli-${{ runner.os }}-${{ inputs.solana-cli-version }}
        restore-keys: |
          solana-cli-${{ runner.os }}-

    - name: Install Solana CLI
      shell: bash
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v${{ inputs.solana-cli-version }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Cache Light CLI
      if: inputs.install-light-cli == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache/npm
        key: light-cli-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml') }}
        restore-keys: |
          light-cli-${{ runner.os }}-

    - name: Install Light CLI
      if: inputs.install-light-cli == 'true'
      shell: bash
      run: npm install -g @lightprotocol/zk-compression-cli@alpha

    - name: Install pnpm
      if: inputs.install-pnpm == 'true'
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup pnpm cache
      if: inputs.install-pnpm == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Cache Photon indexer
      if: inputs.photon-indexer == 'true'
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/photon
        key: photon-${{ runner.os }}-1a785036de52896b68d06413e3b0231122d6aa4a

    - name: Install Photon indexer
      if: inputs.photon-indexer == 'true'
      shell: bash
      env:
        RUSTFLAGS: "-A dead-code"
      run: |
        if [ ! -f ~/.cargo/bin/photon ]; then
          cargo install --git https://github.com/lightprotocol/photon.git --rev 1a785036de52896b68d06413e3b0231122d6aa4a --locked
        fi

    - name: Generate keypair
      shell: bash
      run: solana-keygen new --no-bip39-passphrase

    - name: Display versions
      shell: bash
      run: |
        rustc --version
        cargo --version
        solana --version
        node --version
        if [ "${{ inputs.install-light-cli }}" == "true" ]; then
          light --version
        fi
        if [ "${{ inputs.install-pnpm }}" == "true" ]; then
          pnpm --version
        fi
