[package]
name = "tests-solana-attestation-service"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true }
litesvm = "0.12.0"
solana-attestation-service-client = { workspace = true }
solana-clock = "3.0"
solana-instruction-error = "2.0"
solana-keypair = "3.1"
solana-program-option = "3.0"
solana-program-pack = "3.0"
solana-pubkey = "4.0"
solana-sdk-ids = "3.1"
solana-signer = "3.0"
solana-transaction = "3.0"
solana-transaction-error = "3.0"
spl-token-2022-interface = "3.1.2"
spl-token-group-interface = "0.7.2"
spl-token-metadata-interface = "1.0.1"

[lints]
workspace = true
