[package]
name = "solana-attestation-service-client"
version = { workspace = true }
edition = "2021"
description = "Rust client for the Solana Attestation Service"
license = "MIT"
repository = "https://github.com/solana-foundation/solana-attestation-service"
include = ["Cargo.toml", "src/**/*.rs"]

[features]
default = []
fetch = ["dep:solana-account", "dep:solana-rpc-client"]
serde = ["dep:serde", "dep:serde_with", "solana-address/serde"]

[dependencies]
borsh = { workspace = true, features = ["derive"] }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_with = { workspace = true, optional = true }
solana-account = { workspace = true, optional = true }
solana-account-info = { workspace = true }
solana-address = { workspace = true, features = ["borsh", "copy"] }
solana-cpi = { workspace = true }
solana-instruction = { workspace = true }
solana-program-error = { workspace = true }
solana-rpc-client = { workspace = true, optional = true }
thiserror = { workspace = true }
