[package]
name = "sas-standard-demo"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0"
borsh = { version = "1.5.5", features = ["derive"] }
solana-address = { version = "2.8.0", features = ["curve25519"] }
solana-attestation-service-client = { version = "2.0.0", path = "../../../../clients/rust" }
solana-commitment-config = "3.1"
solana-compute-budget-interface = "3.1"
solana-instruction = "3.1"
solana-keypair = "3.1"
solana-message = "3.1"
solana-native-token = "3.0"
solana-rpc-client = "3.1.8"
solana-signer = "3.0"
solana-transaction = "3.0"
